//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHesabim.Framework.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Headers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Headers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eHesabim.Framework.Localization.Headers", typeof(Headers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Ekle/Düzenle.
        /// </summary>
        public static string BankAccountEdit {
            get {
                return ResourceManager.GetString("BankAccountEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesaplar.
        /// </summary>
        public static string BankAccountList {
            get {
                return ResourceManager.GetString("BankAccountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesaplar.
        /// </summary>
        public static string BankAccounts {
            get {
                return ResourceManager.GetString("BankAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Hareket Ekle/Düzenle.
        /// </summary>
        public static string BankAccountTransactionEdit {
            get {
                return ResourceManager.GetString("BankAccountTransactionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Hareketleri.
        /// </summary>
        public static string BankAccountTransactionList {
            get {
                return ResourceManager.GetString("BankAccountTransactionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Ekle.
        /// </summary>
        public static string BankCreditAdd {
            get {
                return ResourceManager.GetString("BankCreditAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Kartı Ekle/Düzenle.
        /// </summary>
        public static string BankCreditCardEdit {
            get {
                return ResourceManager.GetString("BankCreditCardEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Kartları.
        /// </summary>
        public static string BankCreditCardList {
            get {
                return ResourceManager.GetString("BankCreditCardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.Kartı Ödeme Ekle/Düzenle.
        /// </summary>
        public static string BankCreditCardPaymentEdit {
            get {
                return ResourceManager.GetString("BankCreditCardPaymentEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.Kartı Ödemeleri.
        /// </summary>
        public static string BankCreditCardPaymentList {
            get {
                return ResourceManager.GetString("BankCreditCardPaymentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.Kartı Dönem Ekle/Düzenle.
        /// </summary>
        public static string BankCreditCardPeriodEdit {
            get {
                return ResourceManager.GetString("BankCreditCardPeriodEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.Kartı Dönemleri.
        /// </summary>
        public static string BankCreditCardPeriodList {
            get {
                return ResourceManager.GetString("BankCreditCardPeriodList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Kartları.
        /// </summary>
        public static string BankCreditCards {
            get {
                return ResourceManager.GetString("BankCreditCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Düzenle.
        /// </summary>
        public static string BankCreditEdit {
            get {
                return ResourceManager.GetString("BankCreditEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krediler.
        /// </summary>
        public static string BankCreditList {
            get {
                return ResourceManager.GetString("BankCreditList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krediler.
        /// </summary>
        public static string BankCredits {
            get {
                return ResourceManager.GetString("BankCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Taksiti Düzenle.
        /// </summary>
        public static string BankCreditSubEdit {
            get {
                return ResourceManager.GetString("BankCreditSubEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Taksitleri.
        /// </summary>
        public static string BankCreditSubList {
            get {
                return ResourceManager.GetString("BankCreditSubList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Ekstre.
        /// </summary>
        public static string CustomerAbstract {
            get {
                return ResourceManager.GetString("CustomerAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Ekle/Düzenle.
        /// </summary>
        public static string CustomerEdit {
            get {
                return ResourceManager.GetString("CustomerEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Kartlar.
        /// </summary>
        public static string CustomerList {
            get {
                return ResourceManager.GetString("CustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hareket Ekle/Düzenle.
        /// </summary>
        public static string CustomerTransactionEdit {
            get {
                return ResourceManager.GetString("CustomerTransactionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Hareketler.
        /// </summary>
        public static string CustomerTransactionList {
            get {
                return ResourceManager.GetString("CustomerTransactionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harcama Ekle/Düzenle.
        /// </summary>
        public static string ExpenseEdit {
            get {
                return ResourceManager.GetString("ExpenseEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider Grubu Düzenle.
        /// </summary>
        public static string ExpenseGroupEdit {
            get {
                return ResourceManager.GetString("ExpenseGroupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider Grupları.
        /// </summary>
        public static string ExpenseGroupList {
            get {
                return ResourceManager.GetString("ExpenseGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider Raporu.
        /// </summary>
        public static string ExpenseGroupReport {
            get {
                return ResourceManager.GetString("ExpenseGroupReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harcamalar.
        /// </summary>
        public static string ExpenseList {
            get {
                return ResourceManager.GetString("ExpenseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağaza Düzenle.
        /// </summary>
        public static string ExpenseStoreEdit {
            get {
                return ResourceManager.GetString("ExpenseStoreEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağazalar.
        /// </summary>
        public static string ExpenseStoreList {
            get {
                return ResourceManager.GetString("ExpenseStoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Değiştir.
        /// </summary>
        public static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Kurtarma.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre Belirle.
        /// </summary>
        public static string PasswordRecoveryConfirm {
            get {
                return ResourceManager.GetString("PasswordRecoveryConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetki Ekle/Düzenle.
        /// </summary>
        public static string PermissionEdit {
            get {
                return ResourceManager.GetString("PermissionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkiler.
        /// </summary>
        public static string PermissionList {
            get {
                return ResourceManager.GetString("PermissionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roller.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil Güncelle.
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ekle.
        /// </summary>
        public static string UserAdd {
            get {
                return ResourceManager.GetString("UserAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Düzenle.
        /// </summary>
        public static string UserEdit {
            get {
                return ResourceManager.GetString("UserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışılan Modüller.
        /// </summary>
        public static string UserModule {
            get {
                return ResourceManager.GetString("UserModule", resourceCulture);
            }
        }
    }
}
