//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHesabim.Framework.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eHesabim.Framework.Localization.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMH Limiti.
        /// </summary>
        public static string AccountLimit {
            get {
                return ResourceManager.GetString("AccountLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Adı.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Tipi.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Satırı.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varlık Toplamı.
        /// </summary>
        public static string AssetTotal {
            get {
                return ResourceManager.GetString("AssetTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalan Limit.
        /// </summary>
        public static string AvailableLimit {
            get {
                return ResourceManager.GetString("AvailableLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakiye.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap.
        /// </summary>
        public static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi.
        /// </summary>
        public static string BankCredit {
            get {
                return ResourceManager.GetString("BankCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.Kartı.
        /// </summary>
        public static string BankCreditCard {
            get {
                return ResourceManager.GetString("BankCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçerlilik.
        /// </summary>
        public static string BankCreditCardExpired {
            get {
                return ResourceManager.GetString("BankCreditCardExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçerlilik (Ay).
        /// </summary>
        public static string BankCreditCardExpiredMonth {
            get {
                return ResourceManager.GetString("BankCreditCardExpiredMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçerlilik (Yıl).
        /// </summary>
        public static string BankCreditCardExpiredYear {
            get {
                return ResourceManager.GetString("BankCreditCardExpiredYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Limiti.
        /// </summary>
        public static string BankCreditCardLimit {
            get {
                return ResourceManager.GetString("BankCreditCardLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Adı.
        /// </summary>
        public static string BankCreditCardName {
            get {
                return ResourceManager.GetString("BankCreditCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Bin.
        /// </summary>
        public static string BankCreditCardNo {
            get {
                return ResourceManager.GetString("BankCreditCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlı Kart.
        /// </summary>
        public static string BankCreditCardParent {
            get {
                return ResourceManager.GetString("BankCreditCardParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dön..
        /// </summary>
        public static string BankCreditCardPeriod {
            get {
                return ResourceManager.GetString("BankCreditCardPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekstre Dönemi.
        /// </summary>
        public static string BankCreditCardPeriod2 {
            get {
                return ResourceManager.GetString("BankCreditCardPeriod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silme.
        /// </summary>
        public static string CanDelete {
            get {
                return ResourceManager.GetString("CanDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekleme.
        /// </summary>
        public static string CanInsert {
            get {
                return ResourceManager.GetString("CanInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okuma.
        /// </summary>
        public static string CanRead {
            get {
                return ResourceManager.GetString("CanRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme.
        /// </summary>
        public static string CanUpdate {
            get {
                return ResourceManager.GetString("CanUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anapara.
        /// </summary>
        public static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anapara Tutarı.
        /// </summary>
        public static string CapitalAmount {
            get {
                return ResourceManager.GetString("CapitalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alacak (-).
        /// </summary>
        public static string Claim {
            get {
                return ResourceManager.GetString("Claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (-) Alacak Toplamı.
        /// </summary>
        public static string ClaimTotal {
            get {
                return ResourceManager.GetString("ClaimTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe.
        /// </summary>
        public static string County {
            get {
                return ResourceManager.GetString("County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eklenme Tarihi.
        /// </summary>
        public static string CreatedDateTime {
            get {
                return ResourceManager.GetString("CreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Bilgisi.
        /// </summary>
        public static string CreditInfo {
            get {
                return ResourceManager.GetString("CreditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dönem İçi.
        /// </summary>
        public static string CurrentDebt {
            get {
                return ResourceManager.GetString("CurrentDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harici Cari.
        /// </summary>
        public static string CustomerExclusion {
            get {
                return ResourceManager.GetString("CustomerExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harici Cari.
        /// </summary>
        public static string CustomerIsExclusion {
            get {
                return ResourceManager.GetString("CustomerIsExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Adı.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borç (+).
        /// </summary>
        public static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borç / Alacak.
        /// </summary>
        public static string DebitClaim {
            get {
                return ResourceManager.GetString("DebitClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (+) Borç Toplamı.
        /// </summary>
        public static string DebitTotal {
            get {
                return ResourceManager.GetString("DebitTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borç Toplamı.
        /// </summary>
        public static string DebtTotal {
            get {
                return ResourceManager.GetString("DebtTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vade Tarihi.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vadesi Gelen.
        /// </summary>
        public static string DueDebit {
            get {
                return ResourceManager.GetString("DueDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masraf.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harici Harcama.
        /// </summary>
        public static string ExpenseExclusion {
            get {
                return ResourceManager.GetString("ExpenseExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider Grubu.
        /// </summary>
        public static string ExpenseGroup {
            get {
                return ResourceManager.GetString("ExpenseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G. Grubu.
        /// </summary>
        public static string ExpenseGroup2 {
            get {
                return ResourceManager.GetString("ExpenseGroup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider Grubu.
        /// </summary>
        public static string ExpenseGroupName {
            get {
                return ResourceManager.GetString("ExpenseGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider Grubu Ekle.
        /// </summary>
        public static string ExpenseGroupNotExists {
            get {
                return ResourceManager.GetString("ExpenseGroupNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harici Harcama.
        /// </summary>
        public static string ExpenseIsExclusion {
            get {
                return ResourceManager.GetString("ExpenseIsExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harcamalarım.
        /// </summary>
        public static string ExpenseMe {
            get {
                return ResourceManager.GetString("ExpenseMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonraki Dönem.
        /// </summary>
        public static string ExpenseNextPeriod {
            get {
                return ResourceManager.GetString("ExpenseNextPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string ExpenseNotes {
            get {
                return ResourceManager.GetString("ExpenseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağaza.
        /// </summary>
        public static string ExpenseStore {
            get {
                return ResourceManager.GetString("ExpenseStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağaza Adı.
        /// </summary>
        public static string ExpenseStoreName {
            get {
                return ResourceManager.GetString("ExpenseStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağaza Ekle.
        /// </summary>
        public static string ExpenseStoreNotExists {
            get {
                return ResourceManager.GetString("ExpenseStoreNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Harcama.
        /// </summary>
        public static string ExpenseTotal {
            get {
                return ResourceManager.GetString("ExpenseTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harcama Tipi.
        /// </summary>
        public static string ExpenseType {
            get {
                return ResourceManager.GetString("ExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H. Türü.
        /// </summary>
        public static string ExpenseType2 {
            get {
                return ResourceManager.GetString("ExpenseType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay.
        /// </summary>
        public static string Explanation {
            get {
                return ResourceManager.GetString("Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belge.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puan.
        /// </summary>
        public static string HasPoint {
            get {
                return ResourceManager.GetString("HasPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN No.
        /// </summary>
        public static string Iban {
            get {
                return ResourceManager.GetString("Iban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taksit.
        /// </summary>
        public static string Installment {
            get {
                return ResourceManager.GetString("Installment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taksit Tutarı.
        /// </summary>
        public static string InstallmentAmount {
            get {
                return ResourceManager.GetString("InstallmentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taksit Tarihi.
        /// </summary>
        public static string InstallmentDate {
            get {
                return ResourceManager.GetString("InstallmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string InstallmentNo {
            get {
                return ResourceManager.GetString("InstallmentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam.
        /// </summary>
        public static string InstallmentTotal {
            get {
                return ResourceManager.GetString("InstallmentTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faiz Tutarı.
        /// </summary>
        public static string InterestAmount {
            get {
                return ResourceManager.GetString("InterestAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrc..
        /// </summary>
        public static string IsExclusion {
            get {
                return ResourceManager.GetString("IsExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciro.
        /// </summary>
        public static string IsSales {
            get {
                return ResourceManager.GetString("IsSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekstre Borcu.
        /// </summary>
        public static string LastDebt {
            get {
                return ResourceManager.GetString("LastDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aylık Ödeme.
        /// </summary>
        public static string MonthlyPayment {
            get {
                return ResourceManager.GetString("MonthlyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocak;Şubat;Mart;Nisan;Mayıs;Haziran;Temmuz;Ağustos;Eylül;Ekim;Kasım;Aralık.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oca.;Şub.;Mar.;Nis.;May.;Haz.;Tem.;Ağu.;Eyl.;Eki.;Kas.;Ara.;Toplam.
        /// </summary>
        public static string Months2 {
            get {
                return ResourceManager.GetString("Months2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakiye.
        /// </summary>
        public static string Net {
            get {
                return ResourceManager.GetString("Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakiye.
        /// </summary>
        public static string NetTotal {
            get {
                return ResourceManager.GetString("NetTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonraki Dönem.
        /// </summary>
        public static string NextDebt {
            get {
                return ResourceManager.GetString("NextDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notlar.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıra.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer Hesap.
        /// </summary>
        public static string OtherBankAccount {
            get {
                return ResourceManager.GetString("OtherBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Tarihi.
        /// </summary>
        public static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öd..
        /// </summary>
        public static string PaymentDate2 {
            get {
                return ResourceManager.GetString("PaymentDate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Toplamı.
        /// </summary>
        public static string PaymentTotal {
            get {
                return ResourceManager.GetString("PaymentTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oran.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalan Anapara.
        /// </summary>
        public static string RemainCapital {
            get {
                return ResourceManager.GetString("RemainCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalan Taksit.
        /// </summary>
        public static string RemainInstallment {
            get {
                return ResourceManager.GetString("RemainInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre (Tekrar).
        /// </summary>
        public static string RePassword {
            get {
                return ResourceManager.GetString("RePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to « Seçiniz ».
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harcamaları Ata.
        /// </summary>
        public static string SetExpensePeriod {
            get {
                return ResourceManager.GetString("SetExpensePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap.
        /// </summary>
        public static string ShowAccount {
            get {
                return ResourceManager.GetString("ShowAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.Kartı.
        /// </summary>
        public static string ShowCard {
            get {
                return ResourceManager.GetString("ShowCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi.
        /// </summary>
        public static string ShowCredit {
            get {
                return ResourceManager.GetString("ShowCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari.
        /// </summary>
        public static string ShowCustomer {
            get {
                return ResourceManager.GetString("ShowCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harici Carileri Göster.
        /// </summary>
        public static string ShowCustomerExclusion {
            get {
                return ResourceManager.GetString("ShowCustomerExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider.
        /// </summary>
        public static string ShowExpense {
            get {
                return ResourceManager.GetString("ShowExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dönem.
        /// </summary>
        public static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
