//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHesabim.Framework.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eHesabim.Framework.Localization.Menus", typeof(Menus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesaplar.
        /// </summary>
        public static string BankAccounts {
            get {
                return ResourceManager.GetString("BankAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Hareketleri.
        /// </summary>
        public static string BankAccountTransactions {
            get {
                return ResourceManager.GetString("BankAccountTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.Kartı Ödemeleri.
        /// </summary>
        public static string BankCreditCardPayments {
            get {
                return ResourceManager.GetString("BankCreditCardPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.Kartı Dönemleri.
        /// </summary>
        public static string BankCreditCardPeriods {
            get {
                return ResourceManager.GetString("BankCreditCardPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Kartları.
        /// </summary>
        public static string BankCreditCards {
            get {
                return ResourceManager.GetString("BankCreditCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krediler.
        /// </summary>
        public static string BankCredits {
            get {
                return ResourceManager.GetString("BankCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Taksitleri.
        /// </summary>
        public static string BankCreditSubs {
            get {
                return ResourceManager.GetString("BankCreditSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Ekstre.
        /// </summary>
        public static string CustomerAbstract {
            get {
                return ResourceManager.GetString("CustomerAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Kartlar.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Hareketler.
        /// </summary>
        public static string CustomerTransactions {
            get {
                return ResourceManager.GetString("CustomerTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider Raporu.
        /// </summary>
        public static string ExpenseGroupReport {
            get {
                return ResourceManager.GetString("ExpenseGroupReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider Grupları.
        /// </summary>
        public static string ExpenseGroups {
            get {
                return ResourceManager.GetString("ExpenseGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harcamalar.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağazalar.
        /// </summary>
        public static string ExpenseStores {
            get {
                return ResourceManager.GetString("ExpenseStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkiler.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistem.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
