//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHesabim.Framework.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eHesabim.Framework.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem için yetkiniz yok..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir Tutar giriniz..
        /// </summary>
        public static string AmountMustBeNumber {
            get {
                return ResourceManager.GetString("AmountMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt silinecek, emin misiniz?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta yada şifreniz hatalı..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir E-Posta giriniz..
        /// </summary>
        public static string MustBeEmailFormat {
            get {
                return ResourceManager.GetString("MustBeEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir değer giriniz..
        /// </summary>
        public static string MustBeNumber {
            get {
                return ResourceManager.GetString("MustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz değiştirilmiştir..
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreler Uyuşmuyor..
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre belirleme işlemi başarısız..
        /// </summary>
        public static string PasswordRecoveryConfirmError {
            get {
                return ResourceManager.GetString("PasswordRecoveryConfirmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt bulunamadı..
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporlanacak veri bulunamadı..
        /// </summary>
        public static string ReportDataEmpty {
            get {
                return ResourceManager.GetString("ReportDataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zorunlu Alan.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Hesap Adı giriniz..
        /// </summary>
        public static string RequiredAccountName {
            get {
                return ResourceManager.GetString("RequiredAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Hesap Tipi seçiniz..
        /// </summary>
        public static string RequiredAccountType {
            get {
                return ResourceManager.GetString("RequiredAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Tutar giriniz..
        /// </summary>
        public static string RequiredAmount {
            get {
                return ResourceManager.GetString("RequiredAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Banka seçiniz..
        /// </summary>
        public static string RequiredBank {
            get {
                return ResourceManager.GetString("RequiredBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Kredi seçiniz..
        /// </summary>
        public static string RequiredBankCredit {
            get {
                return ResourceManager.GetString("RequiredBankCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Kredi Kartı seçiniz..
        /// </summary>
        public static string RequiredBankCreditCard {
            get {
                return ResourceManager.GetString("RequiredBankCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Anapara giriniz..
        /// </summary>
        public static string RequiredCapital {
            get {
                return ResourceManager.GetString("RequiredCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Kart Adı giriniz..
        /// </summary>
        public static string RequiredCardName {
            get {
                return ResourceManager.GetString("RequiredCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Kart No giriniz..
        /// </summary>
        public static string RequiredCardNo {
            get {
                return ResourceManager.GetString("RequiredCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Cari seçiniz..
        /// </summary>
        public static string RequiredCustomer {
            get {
                return ResourceManager.GetString("RequiredCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Tarih seçiniz..
        /// </summary>
        public static string RequiredDate {
            get {
                return ResourceManager.GetString("RequiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen E-Posta giriniz..
        /// </summary>
        public static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Bitiş Tarihi seçiniz..
        /// </summary>
        public static string RequiredEndDate {
            get {
                return ResourceManager.GetString("RequiredEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Masraf giriniz..
        /// </summary>
        public static string RequiredExpense {
            get {
                return ResourceManager.GetString("RequiredExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Gider Grubu seçiniz..
        /// </summary>
        public static string RequiredExpenseGroup {
            get {
                return ResourceManager.GetString("RequiredExpenseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Gider Grubu giriniz..
        /// </summary>
        public static string RequiredExpenseGroupName {
            get {
                return ResourceManager.GetString("RequiredExpenseGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Mağaza seçiniz..
        /// </summary>
        public static string RequiredExpenseStore {
            get {
                return ResourceManager.GetString("RequiredExpenseStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Mağaza adı giriniz..
        /// </summary>
        public static string RequiredExpenseStoreName {
            get {
                return ResourceManager.GetString("RequiredExpenseStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Harcama Tipi seçiniz..
        /// </summary>
        public static string RequiredExpenseType {
            get {
                return ResourceManager.GetString("RequiredExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen zorunlu alanları giriniz..
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Taksit giriniz..
        /// </summary>
        public static string RequiredInstallment {
            get {
                return ResourceManager.GetString("RequiredInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Aylık Ödeme giriniz..
        /// </summary>
        public static string RequiredMonthlyPayment {
            get {
                return ResourceManager.GetString("RequiredMonthlyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Şifre giriniz..
        /// </summary>
        public static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Ödeme Tutarı giriniz..
        /// </summary>
        public static string RequiredPaymentAmount {
            get {
                return ResourceManager.GetString("RequiredPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Ödeme Tarihi seçiniz..
        /// </summary>
        public static string RequiredPaymentDate {
            get {
                return ResourceManager.GetString("RequiredPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Ödeme Tarihi seçiniz..
        /// </summary>
        public static string RequiredPaymentDateTime {
            get {
                return ResourceManager.GetString("RequiredPaymentDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Oran giriniz..
        /// </summary>
        public static string RequiredRate {
            get {
                return ResourceManager.GetString("RequiredRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Şifreyi tekrar giriniz..
        /// </summary>
        public static string RequiredRePassword {
            get {
                return ResourceManager.GetString("RequiredRePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Başlangıç Tarihi seçiniz..
        /// </summary>
        public static string RequiredStartDate {
            get {
                return ResourceManager.GetString("RequiredStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Açıklama giriniz..
        /// </summary>
        public static string RequiredTrnName {
            get {
                return ResourceManager.GetString("RequiredTrnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Borç / Alacak seçiniz..
        /// </summary>
        public static string RequiredTrnType {
            get {
                return ResourceManager.GetString("RequiredTrnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Ad Soyad giriniz..
        /// </summary>
        public static string RequiredUserName {
            get {
                return ResourceManager.GetString("RequiredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Rol seçiniz..
        /// </summary>
        public static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta adresi bulunamadı..
        /// </summary>
        public static string SendPasswordGuidError {
            get {
                return ResourceManager.GetString("SendPasswordGuidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre kurtarma linki başarıyla gönderildi..
        /// </summary>
        public static string SendPasswordGuidSuccess {
            get {
                return ResourceManager.GetString("SendPasswordGuidSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harcamaların ilgili döneme otomatik atanması başarıyla yapılmıştır..
        /// </summary>
        public static string SetPeriodSuccesfully {
            get {
                return ResourceManager.GetString("SetPeriodSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen şifrenizi 6 ila 10 karater uzunluğunda belirleyiniz..
        /// </summary>
        public static string StringLengthPassword {
            get {
                return ResourceManager.GetString("StringLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu E-Posta ile daha öncesinde üyelik oluşturulmuştur..
        /// </summary>
        public static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir değer giriniz. (0 - 120 aralığında).
        /// </summary>
        public static string ValueMustBeOneHundredTwenty {
            get {
                return ResourceManager.GetString("ValueMustBeOneHundredTwenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir değer giriniz. (0 - 100 aralığında).
        /// </summary>
        public static string ValueMustBeZeroHundred {
            get {
                return ResourceManager.GetString("ValueMustBeZeroHundred", resourceCulture);
            }
        }
    }
}
